---
abstract: 'a client library for App::Notifier::Service'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Notifier-Client
requires:
  Getopt::Long: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  URI: 0
  strict: 0
  warnings: 0
version: 0.0101
